version: "3.8"
services:
  discovery-service:
    image: salmaba/discovery-service:latest
    ports:
      - "8761:8761"
    environment:
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin
    networks:
      - microservices-net


  gateway-service:
    image: salmaba/gateway-service:latest
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://admin:admin@discovery-service:8761/eureka/
    networks:
      - microservices-net


  projet-service:
    image: salmaba/projet-service:latest
    ports:
      - "8080:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://admin:admin@discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://projetdb:3306/projetConstruction
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - discovery-service
      - projetdb
    networks:
      - microservices-net


  ressource-service:
    image: salmaba/ressource-service:latest
    ports:
      - "8082:8082"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://admin:admin@discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://ressourcedb:3306/ressourceConstruction
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - discovery-service
      - ressourcedb
    networks:
      - microservices-net


  tache-service:
    image: salmaba/tache-service:latest
    ports:
      - "8081:8081"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://admin:admin@discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://tachedb:3306/tacheConstruction
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - discovery-service
      - tachedb
    networks:
      - microservices-net

  # User Service
  user-service:
    image: salmaba/user-service:latest
    ports:
      - "8087:8087"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://admin:admin@discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://userdb:3306/userConstruction
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - discovery-service
      - userdb
    networks:
      - microservices-net
    deploy:
      restart_policy:
        condition: on-failure

  # Bases de données pour chaque service
  projetdb:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: projetConstruction
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - projet-db:/var/lib/mysql
    networks:
      - microservices-net

  ressourcedb:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: ressourceConstruction
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ressource-db:/var/lib/mysql
    networks:
      - microservices-net

  tachedb:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: tacheConstruction
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - tache-db:/var/lib/mysql
    networks:
      - microservices-net

  userdb:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: userConstruction
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - user-db:/var/lib/mysql
    networks:
      - microservices-net

volumes:
  projet-db:
  ressource-db:
  tache-db:
  user-db:

networks:
  microservices-net:
    driver: bridge
