spring:
  application:
    name: tache-service
  datasource:
    #url: jdbc:mysql://tachedb:3306/tacheConstruction?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/tacheConstruction?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    validate-on-migrate: true

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/


