spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id : r1
            uri: http://localhost:8080/
            predicates:
              - Path=/projets/**
          - id: r2
            uri: http://localhost:8081/
            predicates:
              - Path=/taches/**
          - id: r3
            uri: http://localhost:8082/
            predicates:
              - Path=/ressources/**

server:
  port: 8888

