spring:
  application:
    name: discovery-service
  security:
    user:
      name: admin
      password: admin
      roles: USER
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration



server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

