spring:
  application:
    name: projet-service
  datasource:
    #url: jdbc:mysql://projetdb:3306/projetConstruction?createDatabaseIfNotExist=True
    url: jdbc:mysql://localhost:3306/projetConstruction?createDatabaseIfNotExist=True
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    validate-on-migrate: true

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/





